### ISSUE TITLE
An error occurred inside the app installation script

### ISSUE THREAD

**Issue by rmdes** [YunoHost-Apps/prometheus_ynh#3]
### Describe the bug

*An error occurred inside the app installation script*
- it seems the errors comes just after the user/pass creation of the prometheus user
- 
![image](https://user-images.githubusercontent.com/12155003/152119094-e58b2011-a0c8-412c-8ed3-67084ca25e80.png)

### Context

- Hardware: *Olimex2 armbian (brique-internet)*
- YunoHost version: 4.3.6.2
- I have access to my server: 
*all of the ways*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: 
*no*
- Using, or trying to install package version/branch: 

I tried the app package from the dashboard and then tried the testing branch from the terminal. both have the same error/crash at install

### Steps to reproduce

- *If you performed a command from the CLI, the command itself is enough. For example:*
    ```
    sudo yunohost app install https://github.com/YunoHost-Apps/prometheus_ynh/tree/testing --debug
    ```
- *If you used the webadmin, please perform the equivalent command from the CLI first.*
Already did, same error 
- *If the error occurs in your browser, explain what you did:*
   1. *Catalog*
   2. *Install prometheus*
   3. *Crash*
   4. *See log*

### Expected behavior

*Prometheus should install without errors*

### Logs

https://paste.yunohost.org/raw/cireroziru

**Comment by tituspijean** [comment]
Thank you for your report! It looks like your system architecture was not properly parsed by the install script. Can you share the output of the command `uname -m` ?

**Comment by rmdes** [comment]
the output is : `armv7l`

**Comment by tituspijean** [comment]
Can you try this fix? `sudo yunohost app install https://github.com/YunoHost-Apps/prometheus_ynh/tree/fix-arch -f` 🤞

**Comment by rmdes** [comment]
Works smoothly !

![image](https://user-images.githubusercontent.com/12155003/152695640-9f043f8d-493d-427f-ab3c-e1fcaacf6576.png)

**Comment by rmdes** [comment]
Do i need to switch branch, or can I keep this install & get further upgrades ?

**Comment by rmdes** [comment]
I'm going to restart the app but this is the state after install  
![image](https://user-images.githubusercontent.com/12155003/152696088-62c35161-3b6e-4419-a443-44f84a82de65.png)

**Comment by tituspijean** [comment]
> Do i need to switch branch, or can I keep this install & get further upgrades ?

No need, your YunoHost server will indeed keep monitoring the `master` branch and suggest to upgrade whenever it proposes a more recent version of the app.

> this is the state after install

Last commit fixes that, hopefully. Can you uninstall and try again?

**Comment by rmdes** [comment]
Does the name of the branch-fix changed ?

**Comment by tituspijean** [comment]
I've merged the fix, it's now in the main branch. ;)

Basically YunoHost's catalog only looks for the `master` branch. When you install from another branch, it simply won't propose to upgrade it as long as the `master` branch version is not higher than the one you installed (whatever branch it comes from). I hope I'm clear. :)

Closing. 🚀
